


#  花蜜專家
2016-08-02
正確率：87%

**[Bees Rank Pollen by Taste](http://www.scientificamerican.com/podcast/episode/bees-rank-pollen-by-taste/)**

<audio src="file/pollen expert.mp3" controls="controls">
Your browser does not support the audio element.
</audio>



* _Words_ worth to be remembered:
    + bombard `n. 射石炮 v. 炮击，轰炸；连珠炮似的质问（或批评）`
    + bumblebee `n. 大黄蜂`
    + billboard `n. 广告牌；布告板 v. 宣传`
    + nectar `n. 神酒，甜美饮料，甘露，花蜜`
    + pollination `n. 授粉`
    + pollen `n. 花粉 v. 传授花粉给`
    + quinine `n. 奎宁`
    + savor `n. 滋味；气味；食欲 v. 品尝；尽情享受；意味着，带有…的性质；有…的滋味，加调味品于`
    + distasteful `adj. 味道差的,不愉快的,讨厌的`
    + calibrate `v. 测定；校准，调整`
    + anther `n. 雄蕊的花粉囊,花药`
    + buy out `phr. 全部買下`


## 譯文：[來自滬江官網](http://ting.hujiang.com/u2650279/163660262840/)

* _“()”中的是我認爲正確的翻譯_
* _**黑體字**是我認爲翻譯得好的部分_

穿过时代广场——你会被各种广告~~震撼~~(轟炸)的。可是有研究结果显示，一只大黄蜂飞过一片花海的话，和你也会有同样的感觉呢。所以这些花儿就像是这些广告牌，它们也是在宣传一件商品，那就是这美味的花蜜了，并且蜜蜂其实是很挑剔的顾客哦。 这是Anne Leonard， 里诺市的内华达大学中的一位研究授粉的生物学家。

她把一片花海比作为一种花粉市场。那么蜜蜂会选那个方向开始工作呢？ 蜜蜂们可是花蜜研究专家呢。它们 真的很善于对甚至是花蜜中的糖含量这样的细微差别做出评判。它们也会打量一下花的外形和大小，颜色以及气味。现在， Leonard和她的同事们已经发现，大黄蜂也是花粉爱好者呢。

他们是通过在樱桃花粉中掺杂糖粉或者苦奎宁粉的一组实验得出的结论。并且把这些花粉提供给蜜蜂后进行演示，我们真的很的**对此着了魔**——我们已经在实验室里用~~三~~(3)D打印机打印出花朵。而花药部分——花的雄性器官，也就是生出花粉的地方——~~像~~(用的)是烟斗~~通条~~(清理管)~~的管状结构~~。我们~~购买的是~~(買光了)Michael手工艺商品店中的这些烟斗~~通条~~(清理管)并且用在了我们的实验中。

结果显示，蜜蜂会一次又一次的返回同样颜色的会散布甜味花粉的花朵，并且在此处花费更多的采集时间。但是当它们碰到了苦味的花粉后会怎样的？它们会选择一个不同颜色的花朵作为下一站。所有结果显示，除了喜欢花蜜，蜜蜂也会尝花粉哦——并且用这个方法来鉴定花朵的可用性。该研究结果已经发表在~~《生物学报》~~(Biology Letters不知道有沒有官方中文譯名還是保留原名的好)杂志上。

该研究结果意味着，植物们有个愉快的合作伙伴：那么你能不能让你的花粉更有吸引力，以便蜜蜂会采集它？而不是让花粉尝起来很糟糕以至于它们都不愿采太多？ 而这种权衡~~行为~~(的方法)，也就是仔细的调整化学合成——只是在它们繁忙的花粉交易市场中达成的众多交易中的一种。在那里，唯一的目的就是要收获甜蜜。




# 肠道菌减肥计划

**[Fat Gets Gut Bacteria Working against the Waistline](http://www.scientificamerican.com/podcast/episode/fat-gets-gut-bacteria-working-against-the-waistline/)**

<audio src="file/160615MicrobesAppetite.mp3" controls="controls">
Your browser does not support the audio element.
你的瀏覽器不支持音頻播放。請使用chrome科學上網。
</audio>


听写于：2016-8-3 13:55	用时：26:08
正确率：93%	错词：20个

* _Words_ worth to be remembered:
    + serve up `phr. 端上，提供，提出`
    + buildup `n. 组织,组成,增强`
    + acetate `n. 醋酸纤维（素）`
    + plummet `n. 铅锤；坠子 v. 垂直落下；骤然下跌`
    + assortment `n. 花色品种；混合物；分类`
    + curb `n. 限制；路缘，路边 v. 控制，抑制`
    + ghrelinn `n. 胃饥饿素（一种胃肠道激素）`
    + saline `adj. 含鹽的，鹽的 n. 鹽湖；鹽溶液`


## 譯文：[來自滬江官網](http://ting.hujiang.com/u2650279/163660262840/)

* _“()”中的是我認爲正確的翻譯_
* _**黑體字**是我認爲翻譯得好的部分_

认为是你自己难以控制的吃奶酪蛋糕才导致穿不进去紧身牛仔裤？好吧，你体内的细菌也许也要付一些责任的。因为一项最新研究显示，在小鼠的实验中显示肠道内的微生物对高脂肪的膳食做出的响应就是结束开始释放一种可以使哺乳动物感到饥饿的荷尔蒙(激素)，导致他们吃的更多了。该研究已经发表在《自然》杂志上。

之前的研究工作已经显示出糖尿病或者肥胖的个体肠道内的细菌种类与健康人肠道内的细菌种类是不同的。但是，这种细菌组合确实(會造成)~~有助于~~这些(疾病，指的糖尿病或者肥胖)~~体内代谢紊乱的形成~~吗？或者这其实只是~~代谢紊乱后的~~(疾病的)副作用？为了揭开这个谜团，研究人员们喂养实验小鼠高脂肪的膳食。这些小动物们呈现出~~对~~一~~种~~(类)名为乙酸(鹽)的化学物质的积累，特别是在大肠内。

定位显示它们属于肠道细菌，可以生成乙酸(鹽)， 所以它们既有可能就是**始作俑者**呢。因此研究人员们用抗生素或者一种简单的鹽水清洗方法来清除掉可能存在的微生物。 结果发现乙酸(鹽)的含量显著下降。好吧，所以就是吃脂肪的小~~老~~鼠们体内的肠道细菌制造出的乙酸。那么这些乙酸(鹽)是用来干神马的？额，它可以到达神经系统的非自主部分，就是副交感神经系统，用来熄灭要求制造更多胰岛素的信号。不幸的是，这种情况下，乙酸(鹽)还作用于副交感神经系统来刺激制造一种饥饿激素又名生长激素释放肽。而一只动物所~~消耗~~(攝入)的脂肪越多，它产生出的乙酸(鹽)就越多——也就是说有更多的饥饿激素被制造出来，当然，它也会因此吃更多的食物。而细菌便是这整个连锁反应中的起始环节呢。

研究人员现在正在研究是否在人体内也有类似的生化反应事件的发生。如果答案是肯定的，那么(人類很有可能通過獲得較優質的腸內菌羣來控制體重。)~~人们将有可能获得一种更好的分类肠道细菌的方法，并将有助于我们控制自己的体重。~~当然，最好的方法是~~从~~移植(含有優質腸內細菌的糞便)~~实验中找到那些有益的细菌~~——也就是从一个人体内排出的富含细菌的粪便，移植到你的体内。~~理想情况下这种方法可以有助于抑制你的食欲。~~(這畫面光想一想就能抑制你的食欲啊！！)



# 彩票中獎概率之謎
**[Powerball Lottery Winning Made Inevitable (If Not Easy)](http://www.scientificamerican.com/podcast/episode/powerball-lottery-winning-made-inevitable-if-not-easy/)**

<audio src="file/160111LotteryOdds.mp3" controls="controls">
Your browser does not support the audio element.
你的瀏覽器不支持音頻播放。請使用chrome科學上網。
</audio>

听写于：2016-8-4 13:10	用时：44:49
正确率：90%	错词：43个


* _Words_ worth to be remembered:
    * jackpot `n. 头奖；累积赌注金；最大成功`
    * muse `n. 沉思；冥想；缪斯女神 v. 沉思，冥想；沉思地说`
    * thereabout `adv. 在那附近;大约那时`
    * nail-biting `n. 咬指甲癖性,没有办法的状态,束手无策`
    * combo `n. 联合体；结合物；小型爵士乐队`
    * frenzy `n. 狂热；狂暴；狂怒 v. 使狂怒`
    * dead set `n. 决定性攻击，猛烈攻击 adj. 堅定不移的`

## 譯文：[來自滬江官網](http://ting.hujiang.com/u2650279/163628121314/)

* _“()”中的是我認爲正確的翻譯_
* _**黑體字**是我認爲翻譯得好的部分_


书里有这样一个故事,关于那些利用必然规律赢得彩票的人们. 这是数学家David Hand, 他在谈论2014年他自己出版的一本书, 名为Improbability Principle: Why Coincidences, Miracles and Rare Events Happen Every Day.“不可能之规律: 为什么每天都会发生巧合, 奇迹以及及其少见的一些事儿.”必然规律被积极应用到了彩票抽奖当中——某些组数字会被抽中，所以猜中数字组合是一种必然性事件。 关键词是将来有可能，因为有人已经赢得多重美国谈力球彩票大奖过了。也就是说，下次抽奖的奖金，1月13日晚的那次抽奖，已经达到13亿美金。你也可以买一张试试看。或许，正如你曾默默思考过的结果那样，你也许应该把所有可能的数字组合都买下哦。 1992年，Virginia State州的那次彩票，当时是6/44型的彩票——你必须从44个数字中选出六个——也就是说这是个7百万分之一的可能性事件，如果某一个组合的彩票猜中大奖。700万種组合哦。所以如果你买下所有可能的组合，也只会花掉7百万美元而已。 所以他们等待转动奖池积累剩余奖金，所以，这就积累了好几周，最后达到2千7百万美金。 如果你打算花7百万买下所有可能中的彩票，你也必然会最终中奖的。 但是，有好多不同组织参与运作。 实际上，当时的结果是，他们组成了一个2500人的联合机构，每人花差不多3000美金，所以他们最终共同出资7百万美金。 然后，在之后几天里，他们轮流去买彩票——尽可能的买下所有可能出现的中奖组合。 只是尽量去买。因为，这个联合机构~~之打算买下~~(最终也只成功买到)5百万张彩票而已。所以获奖概率就不是必然的了，他们的获奖概率就是5/7。 然而事实是，他们最终还是获得大奖，所以他们确实获得了积累的所有奖金。这个联合组织预先，**组织大家轮流买这些可能获奖的彩票，紧张的计算彩票获奖概率，比一般工作可难多了。** 所以如果你正考虑召集这样一个Powerball彩票联合购买机构，一定要记住这种彩票的获大奖概率只有2亿9千2百万分之一。而彩票是两美金一个号码。所以你和你的伙伴们将需要告到6亿美金才能买到每一个可能的组合，并且利用到这种必然事件规律。如果有其它类似机构购买了同样有可能获奖的号码组合，你们就不得不分享最终大奖，那么你有可能最后只是收支平衡或者甚至还要亏本呢。 ~~为了正确激发你的热情，~~(不是給你的熱情澆冷水，)我不禁回想起统计学家Michael Orkin的智慧，他也是《可能性是多少？每天的生活中都有机会。》这本书的作者。回看一下2001年Powerball的奖池已经积累到了2亿9千5百万美金并且那时的概率也搞，只有一亿7千5百万分之一。Orkin告诉我说，如果你需要驱车10英里去买Powerball彩票的话，你在行车途中出车祸死亡的概率是你能赢得大奖概率的16倍以上。所以，如果你~~十分热切的~~(依然意志坚定地)要买张彩票的话，至少走路去啦。


# 肠道菌群的抗病展望

**[Gut Microbes Lessen Mice Malarial Malaise](http://www.scientificamerican.com/podcast/episode/gut-microbes-lessen-mice-malarial-malaise/)**

<audio src="file/160212MalariaMicrobiome.mp3" controls="controls">
Your browser does not support the audio element.
你的瀏覽器不支持音頻播放。請使用chrome科學上網。
</audio>

听写于：2016-3-8 | 正确率：89%

* _Words_ worth to be remembered:
    * asymptomatic `adj. 无症状的`
    * plasmodium `疟原虫【植】变形`
    * microbiome `微生物菌羣`
    * vendor `n. 摊贩；卖主；供应商；自动售货机`



## 譯文：[來自滬江官網](http://ting.hujiang.com/u2650279/163477837203/)

* _“()”中的是我認爲正確的翻譯_
* _**黑體字**是我認爲翻譯得好的部分_

当一只蚊子把Plasmodium 寄生虫注入到血中, 你便感染了疟疾. 但是也不是感染了就一定会发病.大多数被感染的人只是轻微疟疾或者连感染的症状都没有. 这是Nathan Schmidt, Louisville大学的细胞免疫学家.成百上千的感染病例中只有一小部分会转为急性疟疾症状.

这些疾病严重程度上的变化是遗传因素造成的.或者说,是否病人是属于对此疾病部分免疫,还要感谢之前的感染.但是Schmidt和他的同事已经发现还有一个因素会影响到疾病的程度: 那就是宿主的微生物群.

在实验室的小鼠中进行的试验首先显示出证据: 即使小鼠几乎在遗传特征上是等同的,从不同的来源所购买到的小鼠在它们对感染性疟疾的反应也是不同的.结果显示,正是由于小鼠们有不同的微生物群.

因此研究人员们进行了更多的测试——他们将有抗性和易感性的动物中采集到的肠道细菌移植给没有任何肠道细菌的洁净小鼠。然后再次对它们进行疟疾感染实验，结果现在已经被移植了有抗性微生物混合物的小鼠们再次免于遭受疟疾的严重迫害——或许多亏了它们这些微生物通过某种促进效应，对它们的免疫系统有积极作用。该研究已发表在《美国国家科学研究进展》杂志上。

至于说要优化这些微生物群？我认为我们现在距离做到能够此类对人类有治疗效果的手段还很远。就拿酸奶举个例子吧，对小鼠来讲没有任何促进作用。但是如果真能做到的话，当我们真的找到调治抗疟疾的微生物群配方时，这些研究人员们表示，还真能够用于减弱寄生虫的致病作用。并且或许能拯救更多的生命呢。

# 磕药是种流行病
**[Opioid Epidemic Gets Treatment Prescription](http://www.scientificamerican.com/podcast/episode/opioid-epidemic-gets-treatment-prescription/)**

<audio src="file/160217OpioidEpidemic.mp3" controls="controls">
Your browser does not support the audio element.
你的瀏覽器不支持音頻播放。請使用chrome科學上網。
</audio>

听写于：2016-3-4 | 正确率：90%

* _Words_ worth to be remembered:
    * hooked `adj. 钩状的；吸毒成瘾的；入迷的`
    * resuscitate `v. （使）复苏，复兴`


## 譯文：[來自滬江官網](http://ting.hujiang.com/u2650279/163477867201/)

* _“()”中的是我認爲正確的翻譯_
* _**黑體字**是我認爲翻譯得好的部分_

在美国，我们已经在处理和鸦片有关的流行病了。

Wilson Compton，美国国家健康研究会国家药物滥用研究会副主席。这是他2月12日在华盛顿举行的美国科学进步协会年度会议上的讲话

我们已经看到越来越多的处方被用作非医疗的用途。这些药物是用于治疗疼痛的。

所以很多处方都可以被利用。每年含有鸦片的处方大约有2.6亿张。这些可不是药片，这些是处方哦。所以有更多的药片其中大部分都被用于消遣娱乐以及其它非正常用途。

有些疼痛患者也许就上瘾了。或者他们的药流向了他们的朋友或者亲属被用作娱乐。再或者处方药鸦片使用者也许转而使用了海洛因。

海洛因只是鸦片类药物的另一种形式，所以大脑并不会刻意区分是否它是来自于药房还是街头小贩。

已经正在引起公众健康关注的是过量使用处方类鸦片和海洛因后的死亡率，最近15年来已经显著增加。目前，我们在美国，一年因过量使用此类药物而死亡的人数就接近5万人。

我们该做点儿神马呢？ 我们已经着重于以下三方面。我们需要去阻止，减少处方药的获得机会，因为最终是开出的处方药导致这种流行病的出现。我们需要思考，通过更有利的使用应对药物及时拯救生命——比如纳洛酮，烯丙羟吗啡酮（一种吗啡拮抗药）——用于阻断鸦片的药性。所以，如果有人用药过量后呼吸停止了，我们能及时应用这种药物去治疗他们，我们就能救活他们。这就给我们机会去帮助他们，由此可以引出我们可以做的第三个方面，那就是通过药物辅助治疗的方法实施更有效率的治疗。

但是我们还认为我们需要想出更好的治疗疼痛的方法。非药物的方法，比如用刺激大脑的技术，去治疗疼痛? 采用其它不不含有鸦片相关化合物的药物？这些科学进步所能带给我们的方法使我们能逆转现在每年大量增长的因药物过度使用造成的流行病。




# 甜菜汁的好处
**[Beet Juice Could Help Body Beat Altitude](http://www.scientificamerican.com/podcast/episode/beet-juice-could-help-body-beat-altitude/)**

<audio src="file/151021BeetJuiceAltitude.mp3" controls="controls">
Your browser does not support the audio element.
你的瀏覽器不支持音頻播放。請使用chrome科學上網。
</audio>

听写于：2016-2-25 | 正确率：90%

* _Words_ worth to be remembered:
    * stagger `adj. 蹒跚的；令人惊愕的；难以置信的`
    * huff `v. 深呼吸，气喘吁吁，上气不接下气`
    * contract `v. 收縮`
    * beet `n. 甜菜，甜菜根，糖萝卜`
    * nitrate `n. 硝酸盐;硝酸钾;硝酸钠`
    * acclimatization `n. 服水土,顺应,适应环境`
    * Mout Everest `n. 埃佛勒斯峰(喜马拉雅山主峰之一,中国称珠穆朗玛峰)`


## 譯文：[來自滬江官網](http://ting.hujiang.com/u2650279/163353951916/)

* _“()”中的是我認爲正確的翻譯_
* _**黑體字**是我認爲翻譯得好的部分_

高达14505英尺，Mount Whitney 高耸在加州内华达山脉中。它可是较低的48 座山峰中最高的一座——也就是说每天它能吸引到成百上千的周末勇士来攀登——或者把这些勇士给搞垮。你可以看到他们沿着狭窄的岩石小路上蹒跚而行，上气不接下气，头昏眼花的在高海拔地区的缺氧环境下精疲力尽的抗争着。而一旦他们生病了怎么办呐？

最好的办法就是撤下去啦。这真的是有效的治疗办法。Svein Gaustad是，挪威科技大学的一位生理学家。他说以前的研究表明血管在高海拔地区会趋于收缩。或许因为她们需要氧气来放松——这在山顶上实在是个短缺的物资呢。但或许可以靠膳食给你的血管补充氧气哦： 就就来一杯甜菜汁吧。这里面含有硝酸盐，我们的身体可以将之转化为一氧化氮，这种化合物能保持血管的柔软灵活性。

Gaustad 和他的同事们在尼泊尔的徒步旅行中测试了上述理论，该地区大概有12000英尺。八名志愿者或者饮用一杯普通压榨的甜菜汁，而另一天，甜菜汁是脱硝酸盐的。几小时后，研究人员们用超声波测量了他们的血液流速和动脉的直径。他们发现，饮用普通甜菜汁的人们确实恢复了在低海拔地区时候的血管弹性，而饮用脱硝酸盐的甜菜汁的人们的血管并没有恢复。改研究结果已经发表在《一氧化氮》杂志上。

Gaustad表示，较好地血管功能就有输送更多血液的潜力——并且因此你的身体会获得更多的氧气——到疲劳的肌肉组织。但是他们还不清楚这种转化作用会根据海拔表现的更好。而且，他说，甜菜也没什么害处，但是这些物质还是不能取代合适的环境适应能力。如果我有一瓶甜菜汁随身携带，我一定会食用的。但是光靠喝甜菜汁应该不会支撑你爬上喜马拉雅山的吧。


# 每逢佳节胖三斤
**[Super Bowl Sunday's Food Needs Work](http://www.scientificamerican.com/podcast/episode/super-bowl-sunday-s-food-needs-work/)**

<audio src="file/160206SuperBowlSnax.mp3" controls="controls">
Your browser does not support the audio element.
你的瀏覽器不支持音頻播放。請使用chrome科學上網。
</audio>

听写于：2016-3-1 | 正确率：88%

* _Words_ worth to be remembered:
    * roomy `adj. 广阔的，宽敞的，宽大的`
    * sweatpant `n. 【美】宽松长运动裤`
    * family-size `adj. 适合(足够)全家用的`
    * overindulge `v. [I] 溺爱，过分放任，过分沉溺（与in连用） [T] 过度沉溺，放纵，过分纵情（于）（与in连用）`
    * advocate `n. 拥护者，提倡者；辩护律师；谋利益者 v. 拥护，提倡`
    * **work off** `phr. 宣泄，释放，排解`
    * drumstick `n. 下段鸡腿肉；鼓槌`
    * pretzel `椒盐脆饼干`
    * puny `adj. 微小的,弱小的,微不足道的`
    * touchdown `n. 触地,触地得分,着地,降落`


## 譯文：[來自滬江官網](http://ting.hujiang.com/u2650279/163468731707/)

* _“()”中的是我認爲正確的翻譯_
* _**黑體字**是我認爲翻譯得好的部分_

这就算是个全民游戏日了,如果你是它的粉丝的话,恐怕已经准备好居家服和家庭装芝士玉米立体脆.但是,如果你还担心放纵过渡的话——如果你住在美国，你或许应该——应该从纽约城市食品政策研究中心的公众健康宣讲会上找点儿建议。Charles Platkin建议，有一种方法来避免过度饮食就是先考虑一下你吃这些东西后需要做多少运动来消耗掉所含的热量。

所以，为了准备周日的超级杯——美国食品消费第二大高峰日——Charles Platkin尝试了大量的人们喜爱的零食小吃。并且，他将其所含热量转换为足球运动背景下的一些等量的运动项目。

所以，比如，两角多米诺旗下的全手工意大利辣肠口味的皮萨所含热量大概需要跑11000吗——也就是大概109个足球场 ——速度需要保持每小时5英里。

那么两块肯德基原味鸡块呐? 就随机摆动1561次吧。

为了消耗一片沾有法式洋葱酱料的薯片，你必须要在中场休息的时候跟随酷玩乐队和比昂斯唱满30分钟。

而且仅仅5片椒盐卷饼饼干——是的，一袋里就那么很小的饼干——也需要你蹦蹦跳跳6..5分钟，不管你支持的队伍是否得分晋级。

也就是说吧，如果你想避免看过比赛之后胖三斤，你最好接受这些建议。或者就用芹菜棒代替那些零食好啦。而且如果你想保持当前的各种身体指数，那就必须还不能有任何酱料哦。

# 枪支自杀与公共健康
**[Suicide Differences by Region Related to Gun Availability](http://www.scientificamerican.com/podcast/episode/suicide-differences-by-region-related-to-gun-availability/)**

<audio src="file/160128GunViolence.mp3" controls="controls">
Your browser does not support the audio element.
你的瀏覽器不支持音頻播放。請使用chrome科學上網。
</audio>

听写于：2016-2-22 | 正确率：91%

* _Words_ worth to be remembered:
    * ideation `n. 观念构成`

## 譯文：[來自滬江官網](http://ting.hujiang.com/u2650279/163458963290/)

* _“()”中的是我認爲正確的翻譯_
* _**黑體字**是我認爲翻譯得好的部分_

有件事儿大家都很清楚，在美国，私人拥有枪支的合法增加了家庭成员因暴力死亡的可能性——原因可能是枪支走火，也可能是三角关系引发血案，特别还有可能是自杀。

这是David Hemenway，哈佛人身伤害控制研究中心的负责人。他也是哈佛公共健康T. H. Chan学院的一名健康政策与管理学教授。枪支暴力谈论通常因自杀而草草收场，即便在美国每年大约有32000起火拼死亡案件中有60%都是自杀行为。Hemenway在1月26日举行的哈夫公共健康学院的研讨会上指出枪支暴力犯罪属于公共健康问题。

来自于案例对照研究和生态研究得到的证据是非常有说服力的。比如，为什么不同城市，不同的州，以及美国境内不同区域的自杀率十分的不同？为了解释不同地区的自杀率之间的差异原因，研究结果显示这些原因根本不能用精神疾病的发病率不同来解释，根本不能用精神病医师的数量多少来解释，甚至也根本不能用人群中的自杀倾向或者自杀企图的比例上的差异来解释。真正在美国人口中出现的这种差异的普遍原因就是枪支的数量。因为是用枪支自杀的数量上有差异。

并且，如果没有枪，用枪支自杀的某人很可能本来就不用出现用枪自杀的动机以及后来用枪自杀成功的这种事儿。比如， 在2013年瑞士，有一项研究追踪调查了军火大小被减半后，就有效的把枪从作案凶器中的出现频率降低了一半。整个自杀率下降，而研究人员们估计，所有自杀的研究对象中，有22% 的人，如果可以选择枪这种工具，那么他们才会自杀，用其它工具他们就不进行自杀行为了。 枪支的出现只是使得你结束生命的冲动出现后更加容易的被满足。

含有Hemenway和其它研究人员关于枪支暴力犯罪属于公共健康问题的全部论坛内容已经可以在线收听。只需要用谷歌搜索“Harvard public health forum”选择相应内容即可。

# 抗氧化物的实际功效还不明
**[Antioxidant Use Still Small Mixed Bag](http://www.scientificamerican.com/podcast/episode/antioxidant-use-still-small-mixed-bag/)**

<audio src="file/160201AntioxidantsDiet.mp3" controls="controls">
Your browser does not support the audio element.
你的瀏覽器不支持音頻播放。請使用chrome科學上網。
</audio>

听写于：2016-2-18 | 正确率：89%

* _Words_ worth to be remembered:
    * regimen `n. 生活规则；养生法；政体`
    * across-the-board `adj. 全面的 adv. 全面地`

## 譯文：[來自滬江官網](http://ting.hujiang.com/u2650279/163458953288/)

* _“()”中的是我認爲正確的翻譯_
* _**黑體字**是我認爲翻譯得好的部分_

你每天是不是都要吞很多抗氧化的产品作为营养健康补充？或许有用。。。吧。

很令人吃惊，但即便经过了几十年的研究，我们还不是很清楚它的作用，还没有个定论吧，如果真有什么可见成效，我们也早就该发现了，而不是现在这种状况。

Walter Willett，他是哈佛 T. H. Chan公共健康 学院 营养学系 的主任 。他 在 1月 15日 巨型的 健康与癌症 研讨会上 做出了挑衅一般饮食与健康之间关系的 演讲 。

目前的相关 研究 已经进行了 随机试验 ，发现并没有什么 可见的显著益处。过去曾发现实际上，其中一种抗氧化物质，β-胡萝卜素 在 吸烟和酗酒的人群中与肺癌的患病率增高有关，尽管在一开始就 很 健康的人中并没有发现有 相关风险的增加。所以 即使随机试验给出了不同的 结论，我认为， 抗氧化物也并不是对癌症或者其它 疾病有很神奇效果的一种物质，但是或许它们 确实有促进健康的一些效果。有一个内科医生的健康研究进行了超过12年的随机试验中的例子显示，在研究期间内， 那些服用了β-胡萝卜素的 人群的认知能力比服用安慰剂的人群提高了不少—— 这个研究发现还挺有趣也挺重要的。

所以，抗氧化物也许对某些人来讲能提供一些促健康的益处 。但即便是有好处，对我们饮食和生活方式的影响以至于减少患癌症的风险这方面的作用也是微乎其微，还有许多其它因素都被证明确实会对疾病的发生能起到重要作用。

完整的研讨会包括Willett 和其它研究人员关于健康和饮食关系方面的讨论内容已经在线发布。只需要在 谷歌上搜索“Harvard public health forum”即可。


# 調整飲食習慣永遠都不晚
**[Healthful Diet Switch Helps Even Late in Life](http://www.scientificamerican.com/podcast/episode/healthful-diet-switch-helps-even-late-in-life/)**

<audio src="file/160119LateLifeDietBenefits.mp3" controls="controls">
Your browser does not support the audio element.
你的瀏覽器不支持音頻播放。請使用chrome科學上網。
</audio>

听写于：2016-2-15 | 正确率：90%


## 譯文：[來自滬江官網](http://ting.hujiang.com/u2650279/163446336926/)

* _“()”中的是我認爲正確的翻譯_
* _**黑體字**是我認爲翻譯得好的部分_

要说你的饮食已经很好了吧。也许有很多红肉，特别是加工肉类。或许还有很多有糖饮料。并且你或许已经这样吃了几十年了。那么现在突然要尝试更健康的饮食究竟是为何呢，要是以前不健康的话，也都已经深受其害很久了不是吗？

晚年的生活会有很大不同，比如说衰老加速或者心脏变差，饮食改变能在即使几个月内就减少心脏病复发或者死亡几率。

Walter Willett是哈佛公共健康T. H. Chan 学校的营养系主任。他在1 月15日关于癌症和饮食的论坛上作出的有关饮食和健康与死亡的关系的言论。

所以，不要说做出重要的改变已经太迟了。对糖尿病也是，如果我们改变我们的饮食，几乎立刻就能减少罹患糖尿病的几率。但这也并没有说，你只需要等，直到你老了以后再开始你的健康生活。现在我们正在进行的一些实验显示，女士在青少年时期的饮食，特别是如果她们吃过很多红肉，这会在她们今后的生命中增加他们罹患乳腺疾病的几率。 所以如果你想要你的生活健康，尽可能早的选择一种健康的生活方式是绝对重要的。 如果你总是忽略这些事，那起码现在开始做到也没有太迟。

全部的几小时论坛上都是Willett和其它研究人员们在线讨论饮食和健康相关研究所得到的研究结论。尽请搜索 谷歌网站上的 Harvard public health forum。

# 咖啡机的隐患
**[Espresso Machines Brew a Microbiome of Their Own](http://www.scientificamerican.com/podcast/episode/espresso-machines-brew-a-microbiome-of-their-own/)**

<audio src="file/151201CoffeemakerMicrobiome.mp3" controls="controls">
Your browser does not support the audio element.
你的瀏覽器不支持音頻播放。請使用chrome科學上網。
</audio>

听写于：2016-2-2 | 正确率：91%

* _Words_ worth to be remembered:
    * menagerie `n. 动物园,动物展览`
    * pathogenic `adj. 使生病的,成为病原的,病原性的`
    * zero in `瞄准具校正，调整归零`
    * residue `n. 剩余物；残留物；残余，残渣`
    * enterococcus `肠道球菌; 肠球菌`
    * fecal `adj. 排泄物的,渣滓的`
    * pseudomonas `假单胞菌属; 假单胞细菌属`
    * pod `n. 豆荚，蚕茧 v. 从豆荚中剥出；结豆荚`

## 譯文：[來自滬江官網](http://ting.hujiang.com/u2650279/163382481136/)

* _“()”中的是我認爲正確的翻譯_
* _**黑體字**是我認爲翻譯得好的部分_

你厨房里最有生机的地方是哪儿啊，我是说附着的细菌呐？切菜板？刷碗的海绵？ 或许，你的咖啡机？ 因为即便咖啡因有抗细菌的效果，有研究显示浓缩咖啡机能附着一群细菌——包括一些和厕所马桶有关的致病菌相类似的致病菌呢。

研究人员们对10台Nespresso牌的浓缩咖啡机进行采样，主要范围集中在水盘，那里在煮咖啡之后有些残留暗金色的液滴。他们发现，10台机器中有9台，残留物里含有Enterococcus肠球菌属的细菌，一种人类粪便污染物被细菌感染的标志。另一种Pseudomonas假单胞菌属细菌——则有的是无害的，有些是致病的菌种被发现残留。假单胞菌在有咖啡因存在的情况下会大量繁殖，然后分解咖啡因。这种特性提示我们也许可用它进行去咖啡因咖啡的制作，或者从我们的排水口中清除咖啡因。该研究结果发表在《科学报告》杂志上。

关乎你的下一次煮咖啡嘛？别太担心了。研究人员在咖啡包里没有发现任何种类细菌——因此他们表示我们指尖也许对扩散此类单细胞生物有促进作用。然后他们写道，这绝对不是说浓缩咖啡剂对人类的健康有害。只需要像担心你的其它食物表面会被污染一样，经常用肥皂水清洗一下滴水盘。 所以之后，你的咖啡机里就只有一种你想要煮的，咖啡啦。

# 暴饮暴食有原因
**[Overeating Due to Stress?](http://www.scientificamerican.com/podcast/episode/overeating-due-to-stress-13-11-17/)**

<audio src="file/sa_p_podcast_131117.mp3" controls="controls">
Your browser does not support the audio element.
你的瀏覽器不支持音頻播放。請使用chrome科學上網。
</audio>

听写于：2015-9-18 | 正确率：96%

* _Words_ worth to be remembered:
    * munch `v. 用力咀嚼，大声咀嚼`
    * twist `n. 扭，绞，搓，缠，编；窍门；曲解；扭伤 v. 扭转，扭弯，旋转，绞；缠绕，盘绕；扭伤；歪曲；扭动`


## 譯文：[來自滬江官網](http://ting.hujiang.com/u2650279/163246476969/)

* _“()”中的是我認爲正確的翻譯_
* _**黑體字**是我認爲翻譯得好的部分_

压力可以使某些人（也包括我啦）失去胃口。还有些人会从食物中找到慰籍。但是这样的行为也许会在长时间后得到调和。因为研究人员们发现，因压力而改变饮食模式的人，在没有压力的时候出现的不那么健康的饮食冲动实际上会得到弥补。 这是在《心理学科学》杂志上发表的一项研究得出的结论。

该研究中的志愿者都是自我标榜为“吃货一枚”或者“吃不吃看情况”的人。每隔人都不得不通过视频聊天和另外一个人进行一次互动，目的就是为了之后和他们进行正式会面。每个视频互动过后的参与者会受到一个留言信息，内容是他们的同伴决定不和他们见面了，或者是他们的同伴十分期待和他们会面。对照组中，参与人员们会被告知这次的研究实验活动被取消了。然后，研究人员们为每人准备了冰淇凌——要多少就给多少哦。

被告知会面被拒绝的吃货们比对照组的人吃掉更多的冰淇凌，而被拒绝的 三餐不固定的人则比对照组的人吃的冰淇凌要少。所有的结果都在意料之中。

可是也有个小纠结：在收到积极反馈的参与者们，标榜为吃货的 人比对照组的人吃的冰淇淋少。而三餐不固定的人却吃得比对照组的人多。

所以即便是因压力而吃东西的人有时候也会吃得少一些的。除非他们总是被压力困扰着。

# 化妆品广告的科学依据
**[Cosmetic Ads' Science Claims Lack Foundation](http://www.scientificamerican.com/podcast/episode/cosmetic-ads-science-claims-lack-foundation/)**

<audio src="file/150825CosmeticsAds.mp3" controls="controls">
Your browser does not support the audio element.
你的瀏覽器不支持音頻播放。請使用chrome科學上網。
</audio>

听写于：2015-9-16 | 正确率：84%

* _Words_ worth to be remembered:
    * cosmetic `adj. 表面的；美容的 n. 化妆品，装饰品`
    * outright `adj. 完全的，彻底的；直率的 adv. 完全的，彻底的；即刻；率直地`
    * blatantly `adv. 喧闹地；公然地；露骨地；极为，完全`
    * keep sth. at bay `v. 牵制,不使逼近`


## 譯文：[來自滬江官網](http://ting.hujiang.com/u2650279/163246526971/)

* _“()”中的是我認爲正確的翻譯_
* _**黑體字**是我認爲翻譯得好的部分_


临床实验证实..突破性技术..十年遗传学研究表明..这些词你也许本想在科学美国人的杂志上看到.但是这些描述你也能在化妆品广告和印刷宣传册上见到.

现在有一项研究发现,有些——好吧，有很多——这些坚实的科学声明基本就不是真的。

研究人员们察看了300多份杂志上的广告，比如时尚杂志。他们分析了在广告上的这些声明并把它们按真实程度从可以接受到完全是谎言这样的顺序排名。然后他们发现，宣称该产品被科研人员们检查过后的产品中有18%是真的。由23% 就是谎言。还有42% 说的模棱两可而不好被归类。该研究已发表在《全球时尚营销》杂志上。

食品药品管理局规定什么成分被用在你的化妆品里以及产品说明上应该写什么。如果一项宣称是明显不真实的，那么FDA是可以采取行动处理的。标签上的用词模糊也许是一种阻止 FDA 的一种方法。

同时，广告是被联邦商贸委员会管理的。就在去年，欧莱雅刚刚因为其产品Génifique的虚假广告被罚款，广告中该公司说道，临床证明其商品促基因表达的活性，从而导致引起可以只需要7天便可以使你的皮肤年轻的一些蛋白质被表达出来。一项达成一致的和解迫使欧莱雅撤回这项声明。

所以对化妆品广告可别太当真了——毕竟，如果科学家们已经想到如何退却你的皱纹或者是增长你的睫毛，还能轮得上这些公司？
