# 絲綢之路上的傳染病
[Silk Road Transported Goods--and Disease](http://www.scientificamerican.com/podcast/episode/silk-road-transported-goods-and-disease/)

<audio src="file/160729SilkRoadDisease.mp3" controls="controls">
Your browser does not support the audio element.
你的瀏覽器不支持音頻播放。請使用chrome科學上網。
</audio>


听写于：2016-10-6 12:2	用时：68:10
正确率：91%	错词：43个


<!--我的听写开始-->
提示：<span class="diff_off">红色</span>：错误单词，<span class="diff_add">绿色</span>：补上正确单词，<span                                                                                                                 class="diff_alert">黄色</span>：纠正大小写与标点</div>                                                                                                                 <p class="linetext">For <span class="diff_off">thousand</span> <span class="diff_add">thousands</span> of years, what's called the Silk Road was a group of <span class="diff_off">lands</span> <span class="diff_add">land</span> and sea trade routes that connected the Far East with South Asia, Africa, the Middle East <span class="diff_alert">,</span> and <span class="diff_alert" title="Southern ">southern </span>Europe. Of course, when humans travel <span class="diff_alert">,</span> they carry their pathogens with them. So scientists and historians have wondered if the Silk Road was a transmission route <span class="diff_alert">,</span> not just for goods<span class="diff_alert">,</span> but for infectious disease. </p><p class="linetext">Now we have the first hard evidence of ancient Silk Road travelers spreading their infections. The find comes from a <span class="diff_off">2000-year-old</span> <span class="diff_add">2,000-year-old</span> latrine <span class="diff_alert">,</span> that had first been excavated in 1992. The report is in the Journal of Archaeological Science<span class="diff_off">:</span> <span class="diff_off">Reports</span>. </p><p class="linetext"><span class="diff_add">So</span> <span class="diff_alert" title="The ">the </span>site is a <span class="diff_off">relate</span> <span class="diff_add">relay</span> station on the Silk Road in northwest China. It's just to the eastern end of the Tarim Basin<span class="diff_alert">,</span> which is a large and <span class="diff_off">varied</span> <span class="diff_add">arid</span> area <span class="diff_alert">.</span> <span class="diff_off">It's</span> <span class="diff_add">just</span> <span class="diff_add">to</span> the <span class="diff_alert" title="East ">east </span>of the Taklamakan desert<span class="diff_alert">,</span> <span class="diff_add">and</span> not far from the Gobi Desert. So this is a dry part of China. </p><p class="linetext">Piers Mitchell, <span class="diff_off">a</span> paleopathologist <span class="diff_alert">,</span> at the University of Cambridge<span class="diff_alert">,</span> and one of the study's authors<span class="diff_alert">,</span> along with <span class="diff_off">a</span> <span class="diff_add">his</span> student Ivy Yeh and colleagues in China. </p><p class="linetext">In the latrine, archaeologists found used hygiene sticks <span class="diff_off">rap</span> <span class="diff_add">wrapped</span> with <span class="diff_off">clothes</span><span class="diff_add">cloth</span>. These were used for what you think they were used for. </p><p class="linetext">This <span class="diff_off">escalation</span> <span class="diff_add">excavation</span> was great <span class="diff_alert">.</span> <span class="diff_alert" title="Because ">because </span>the <span class="diff_off">clothes</span> <span class="diff_off">were</span> <span class="diff_add">cloth</span> <span class="diff_add">was</span> still preserved <span class="diff_off">in</span> <span class="diff_add">and</span> the <span class="diff_off">fezzes</span> <span class="diff_off">which</span> <span class="diff_add">feces</span> <span class="diff_add">was</span> still adherent to the <span class="diff_off">clothes</span> <span class="diff_add">cloth</span> on some of the sticks. So the <span class="diff_off">archaeologists</span> <span class="diff_off">tagged</span> <span class="diff_add">archaeologist</span> <span class="diff_add">kept</span> these sticks in the museum. And so my Ph. D. student<span class="diff_alert">,</span> Ivy Yeh, <span class="diff_off">who</span> <span class="diff_off">is</span> <span class="diff_off">the</span> <span class="diff_add">who's</span> first author <span class="diff_off">of</span> <span class="diff_add">on</span> the paper<span class="diff_alert">.</span> <span class="diff_alert">,</span> <span class="diff_alert" title="She ">she </span>went out to China took some scrapings from the <span class="diff_off">fezzes</span> <span class="diff_add">feces</span> adherent to the <span class="diff_off">clothes</span> <span class="diff_add">cloth</span><span class="diff_alert">.</span> <span class="diff_alert" title="so ">So </span>we were <span class="diff_add">then</span> able to analyze that down the microscope when she brought it back to Cambridge. </p><p class="linetext">Where they found <span class="diff_off">legs</span> <span class="diff_add">eggs</span> from parasites <span class="diff_add">-</span> including one from a liver fluke. </p><p class="linetext">And that's the exciting one because that's only found in <span class="diff_off">East</span> <span class="diff_add">eastern</span> and <span class="diff_alert" title="Southern ">southern </span>China and in Korea<span class="diff_alert">.</span> <span class="diff_alert">,</span> <span class="diff_alert" title="Where ">where </span>they have <span class="diff_off">marched</span> <span class="diff_off">the</span> <span class="diff_add">marshy</span> areas that <span class="diff_off">would</span> have the right snails and the right fish. </p><p class="linetext">The fluke needs snails and fish for its lifecycle<span class="diff_alert">.</span> <span class="diff_alert">,</span> <span class="diff_alert" title="But ">but </span>there were no such snails or fish in this dry region of China. So the unlucky <span class="diff_off">travelers</span> <span class="diff_add">traveler</span> who harbored the parasite had to have transported the disease to that spot. </p><p class="linetext">Well <span class="diff_alert">,</span> firstly it tells us that people were doing <span class="diff_off">a</span> very long <span class="diff_off">journey</span><span class="diff_alert">,</span> <span class="diff_add">journeys</span> <span class="diff_add">along</span> the <span class="diff_off">long</span> Silk Road <span class="diff_alert">.</span> <span class="diff_add">and</span> <span class="diff_alert" title="You ">you </span>might think that's obvious<span class="diff_alert">.</span> <span class="diff_alert" title="but ">But </span>no one really knew how long people were traveling. Some people may have been trading, <span class="diff_off">don't</span> <span class="diff_off">need</span> <span class="diff_off">to</span> <span class="diff_off">go</span> <span class="diff_add">only</span> <span class="diff_add">going</span> short distances selling their goods on to the next person. And so the goods might have gone all <span class="diff_off">over</span> the way <span class="diff_off">on</span> <span class="diff_add">along</span> the Silk Road<span class="diff_alert">,</span> but people might not. But we know that some people were doing huge distances. </p><p class="linetext">Secondly <span class="diff_alert">,</span> it shows that <span class="diff_add">you</span> <span class="diff_add">know</span> this <span class="diff_add">was</span><span class="diff_alert">,</span> would be a viable route for the spread of those other infectious diseases like Bubonic plague <span class="diff_alert">,</span> <span class="diff_add">and</span> <span class="diff_alert" title="Leprosy">leprosy </span><span class="diff_alert">,</span> and anthrax <span class="diff_alert">.</span> <span class="diff_add">that</span> <span class="diff_alert" title="People ">people </span>had previously <span class="diff_off">been</span> suggested might have been spread between East Asia and Europe along the Silk Road. Because <span class="diff_off">bone</span> <span class="diff_add">modern</span> genetic analyses have just shown similarities between <span class="diff_add">the</span> strains <span class="diff_add">of</span> one <span class="diff_add">end</span> and the other. </p><p class="linetext">Mitchell says <span class="diff_off">there</span> <span class="diff_off">is</span> <span class="diff_add">there's</span> much more work to be done to better understand the spread of diseases around the world. Perhaps from analyzing skeletons <span class="diff_add">-</span> or various other kinds of remains <span class="diff_add">-</span> to be found along the Silk Road.</p>



* _Words_ worth to be remembered:
    * latrine: `n. a public toilet in a military area`
    * relay: `n. 接力赛；替班；中继设备；转播，传送 v. 传达；转播，传送；（使）接替`
    * arid: `adj. 干旱的，干燥的；贫瘠的，不毛的；枯燥无味的`
    * archaeologist: `n. 考古学家`
    * excavation: `n. 挖掘，发掘；挖，开凿`
    * Taklamakan desert: `塔克拉玛干沙漠`
    * feces: `n. 排泄物，渣滓`
    * Gobi Desert: `戈壁沙漠（蒙古和中国西北部）`
    * marshy: `adj. 多沼地的，湿地的，沼地的`
    * Bubonic plague: `n. [医]黑死病,淋巴腺鼠疫`
    * leprosy:  `n. 麻疯病,腐败`
    * athrax: `n. 炭疽热`


## 譯文
几千年前， 有个被称为丝绸之路的地方就是一段陆地和海洋上的贸易路线图，贯穿远东和南亚，中东以及欧洲南部。 当然，那时候人们在旅途中也是会携带者病菌的。所以，科学家和历史学家早就好奇，是不是丝绸之路不仅仅是贸易通商之路，还是传染性疾病的传播之旅阿。

如今，我们找到第一手资料能够证明古老的丝绸之旅上的商旅们确实也传播了他们感染的传染病。这些证据来自于1992年首次挖掘出的一个具有2000年的公厕。该研究报告已经发表在《考古科学：通报》杂志上。

所以这个位点是一个中国西北部丝绸之路上的一个驿站。它通往塔里木盆地的东部末端，是通往塔克拉玛干沙漠东部的一片较大的草木荒芜地区， 离戈壁滩不是很远。所以这里是中国的一块非常干燥的土地。

这是Piers Mitchell,剑桥大学的一位古生物病理学家，也是这项研究的作者之一，其它参与者是他的学生Piers Mitchell,和中国的一些同事。在这个公厕里，考古学家们发现了使用过的包裹着布料的卫生棒。这些东西就是你想象中的需要用到的那些东西。

这次挖掘的意义重大，因为，织物的保存还是完好的，而粪便仍然还粘附在棒子上的布料上的某些地方。所以考古学家们把这样的一些棍子保存在了博物馆里。并且因此我的博士生Ivy Yeh, 他就是这篇文章的第一作者，她就去中国从那些布料上刮下了一些粪便样品。当她回到剑桥之后，我们才能用显微镜观察分析。他们发现了一些寄生虫的卵——包括一种肝吸虫。

因为这种东西只在东部和南部的中国以及韩国存在，所以这个发现还是令人兴奋的。那些地区 都有沼泽地区，里面生存着合适的宿主蜗牛和鱼类。这种肝吸虫的生活史中需要蜗牛和鱼类，但是在这些干燥的中国地区是没有这类蜗牛和鱼类的。所以，被寄生的这些不幸的旅行者们不得不把这种疾病带到了这个站点。

首先，这告诉我们，人们在丝绸之路上行走了相当长的一段距离，并且，你也许认为这还不时很显然的事情吗。但是，没有人真正了解人们具体行走了多长的距离不是吗。一些人也许一直会做着贸易，只走了较短的距离后就把他们的货物卖给下一个人。而这些货物也许被运送了全程，而人们就不一定都走了全程的。但是我们子回到有些人确实走了很远的距离。

第二点，这表明，这是，也许是传播像 Bubonic plague腺鼠疫，麻风病和炭疽热等其它类传染性疾病的一个可行的途径，这些疾病人们以前曾经假设过也许就是在中亚和欧洲地区沿着丝绸之旅开始流行传播的。因为现代遗传分析已经显示出在这条路一端和另外一端的菌株之间的遗传相似性。

Mitchell 表示，还有很多工作需要做，这样将有助于更好的理解全世界的疾病传播情况。或许是通过分析遗迹残骸骨架——或者其它种类的残留物——未来在丝绸之路上所发现的那些东西，就可以了解了。





# 吃魚油的魚
[Farmed Trout Bred to Fatten Up Fast](https://www.scientificamerican.com/podcast/episode/farmed-trout-bred-to-fatten-up-fast/)

<audio src="file/160706VeggieFish.mp3" controls="controls">
Your browser does not support the audio element.
你的瀏覽器不支持音頻播放。請使用chrome科學上網。
</audio>

听写于：2016-10-7 18:36	用时：20:18正确率：91%	错词：24个

<!--我的听写开始-->
提示：<span class="diff_off">红色</span>：错误单词，<span class="diff_add">绿色</span>：补上正确单词，<span class="diff_alert">黄色</span>：纠正大小写与标点</div>
<p class="linetext">Half of all fish people eat worldwide now come from fish farms. So farms need to do more to keep up with demand. </p><p class="linetext"><span class="diff_off">And</span> <span class="diff_alert" title="if ">If </span>we look to the future<span class="diff_alert">,</span> at today's per <span class="diff_off">capital</span> <span class="diff_add">capita</span> fish intake around the world <span class="diff_alert">.</span> <span class="diff_alert" title="We ">we </span><span class="diff_off">will</span> <span class="diff_add">would</span> need to double aquaculture production<span class="diff_alert">.</span> </p><p class="linetext">Ron Hardy is the University of Idaho's Director of Aquaculture Research. He presented his research at <span class="diff_off">a</span> <span class="diff_add">the</span> recent International Symposium on Fish Nutrition and Feeding in Sun Valley, Idaho<span class="diff_alert">,</span> which <span class="diff_off">him</span> <span class="diff_add">he</span> also chaired. </p><p class="linetext">In the wild<span class="diff_alert">,</span> rainbow trout eat insects and other<span class="diff_alert">,</span> smaller fish. But Hardy says there aren't enough little fish to feed larger fish in the wild and still meet market demand as <span class="diff_add">the</span> human population increases. So he's used <span class="diff_off">selected</span> <span class="diff_add">selective</span> breeding to create strains of farmed fish that get by on food that's less expensive than little fish <span class="diff_alert">.</span> <span class="diff_add">-</span> <span class="diff_alert" title="Feed ">feed </span>made from soybeans<span class="diff_off">corns</span> <span class="diff_alert">,</span> <span class="diff_add">corn</span> and <span class="diff_off">weed</span><span class="diff_add">wheat</span>. </p><p class="linetext">Some of the farmed fish really <span class="diff_off">thrived</span><span class="diff_alert">.</span> <span class="diff_add">thrive</span><span class="diff_add">:</span> 16 years ago<span class="diff_alert">,</span> Hardy had to wait a year for a <span class="diff_alert" title="one pound" >one-pound</span>  trout. These days<span class="diff_alert">,</span> his efforts yield trout up to four times as large in the same amount of time. </p><p class="linetext">So<span class="diff_alert">,</span> it <span class="diff_off">become</span> <span class="diff_off">like</span> <span class="diff_add">would</span> <span class="diff_add">be</span> <span class="diff_add">kind</span> of <span class="diff_add">like</span> <span class="diff_add">if</span> you <span class="diff_off">are</span> <span class="diff_add">were</span> going to <span class="diff_add">you</span> <span class="diff_add">know</span> breed <span class="diff_off">a</span><span class="diff_alert">,</span> I don't know <span class="diff_alert">,</span> <span class="diff_off">box</span> <span class="diff_alert">?</span> <span class="diff_add">dogs</span><span class="diff_alert">.</span> So we've got everything from Rottweilers to <span class="diff_alert">,</span> you know <span class="diff_alert">,</span> little Scotties or whatever. </p><p class="linetext">But the farmed fish <span class="diff_off">aren't</span> <span class="diff_add">are</span> <span class="diff_add">not</span> completely vegetarian. Soybeans don't have skeletons<span class="diff_alert">,</span> they don't have bones <span class="diff_alert">.</span> <span class="diff_alert" title="And ">and </span>the bones in fish meal are <span class="diff_add">a</span> major source of <span class="diff_off">mineral</span> <span class="diff_add">minerals</span> for <span class="diff_add">the</span> fish<span class="diff_alert">,</span> for example. And much like humans, fish diets require omega-3 fatty acids, not found in terrestrial plants. So Hardy has to add a little <span class="diff_alert" title="fish oil" >fish-oil</span>  back into the plant-based feed. For those of us without <span class="diff_off">waiters</span><span class="diff_add">waders</span>, this kind of aquaculture is our best shot at a fish fry.</p>
<!--我的听写结束-->


* _Words_ worth to be remembered:
    * aquaculture: `n. 水产养殖；水产业`
    * get by: `phr. 过得去；过活；通过`
    * trout: `n. 鳟鱼，鲑鱼`
    * wader: `n. 步涉者，涉禽类，钓鱼用的防水长靴`

## 譯文

全世界的人消费的所有鱼类中,有一半现在都来自于渔场.所以渔民们需要更努力工作来保证供给.如果从长计议, 按照当今全世界的人均鱼类消费水平来看,未来水产养殖业的产量需要达到翻倍才可以供应的上.

这是Ron Hardy, University of Idaho水产养殖研究的负责人.他最近在Idaho 的太阳山谷Sun Valley举行的渔业营养与养殖国际论坛上发表了他的相关研究, 他同时也是这次会议的主席.

在野生地区, 红鳟鱼吃昆虫或者是其它小鱼.但是Hardy说, 在野生环境中可没有那么多小鱼供应给大一点的鱼, 随着人类数量的增加, 也没有那么多供应给人类. 所以他就选择性的 用比小鱼便宜的食物饲养人工鱼苗——就是用大豆，玉米和小麦做成的鱼食。

有些鱼苗大量繁殖成功：16年前，Hardy 不得不需要等一年才能得到一个一磅重的鳟鱼。近年来，他的努力所得到的鳟鱼，在同样的养殖时间内在体格上已经达到原来的四倍。所以，比如说你之前饲养的是小狗， 那么我们现在已经有从德国Rottweilers 罗特韦尔犬到小型苏格兰犬等各种品种了。

但是，渔场的鱼并不是完全素食的。大豆没有骨架，它们没有骨头而鱼食中的骨头是鱼类所需的比如说矿物质的主要来源。

和人类十分相似的是，鱼的膳食中也需要欧米伽3不饱和脂肪酸，这在陆地植物中是不含有的。所以，Hardy不得不在植物性的鱼食中再添加一点儿鱼油。**对于我们那些不是捕鱼高手的人来说**，这种水产品可是我们在选择炸鱼食品中最好的选择了吧。




# 挑食的蚊子
[Some Malaria Mosquitoes May Prefer Cows to Us](https://www.scientificamerican.com/podcast/episode/some-malaria-mosquitoes-may-prefer-cows-to-us/)

<audio src="file/160919MosquitoMeals.mp3" controls="controls">
Your browser does not support the audio element.
你的瀏覽器不支持音頻播放。請使用chrome科學上網。
</audio>



听写于：2016-10-13 23:22	用时：24:08
正确率：90%	错词：20个



<!--我的听写开始-->
提示：<span class="diff_off">红色</span>：错误单词，<span class="diff_add">绿色</span>：补上正确单词，<span                                                                                                                class="diff_alert">黄色</span>：纠正大小写与标点</div>
<p class="linetext">As you've probably experienced <span class="diff_off">first</span> <span class="diff_off">hand</span> <span class="diff_add">firsthand</span><span class="diff_alert">,</span> some <span class="diff_off">mosquitos</span> <span class="diff_add">mosquito</span> species have a real taste for warm<span class="diff_alert">,</span> human blood. So much so that if you raise them on <span class="diff_off">in</span> <span class="diff_off">a</span> <span class="diff_add">it</span> <span class="diff_add">the</span> lab<span class="diff_off">except</span> <span class="diff_alert">,</span> <span class="diff_add">they'll</span> <span class="diff_add">accept</span> no substitute. </p><p class="linetext">Fortunately, I don't get <span class="diff_off">a</span> major <span class="diff_off">reaction</span> <span class="diff_add">reactions</span> at all. Brad Main is a mosquito geneticist at U. C. Davis <span class="diff_alert">.</span> <span class="diff_alert" title="And ">and </span><span class="diff_alert" title="part time" >part-time</span>  mosquito meal provider. <span class="diff_add">So</span> <span class="diff_alert" title="It's ">it's </span>not too bad for me. But some people in the lab are itching <span class="diff_alert">.</span> <span class="diff_alert" title="Pretty ">pretty </span>bad when they have hundreds of mosquito <span class="diff_off">bite</span> <span class="diff_add">bites</span> on their arms. </p><p class="linetext">Out in the wild, some species are less picky. Take <span class="diff_alert" title="anopheles ">Anopheles </span>arabiensis, common in East Africa. <span class="diff_off">They</span> <span class="diff_off">will</span> <span class="diff_add">They'll</span> feed on cattle, dogs, goats, pigs, people <span class="diff_alert">,</span> <span class="diff_add">-</span> wherever they can find a warm meal. But what Main and his colleagues wanted to know was whether the <span class="diff_off">blood</span> <span class="diff_off">suckers</span> <span class="diff_add">bloodsuckers</span><span class="diff_add">'</span> choice <span class="diff_off">a</span> <span class="diff_add">of</span> victim might be genetically determined. So they sequenced the genomes of 48 arabiensis <span class="diff_off">mosquitos</span> <span class="diff_add">mosquitoes</span> from Tanzania <span class="diff_alert">,</span> which had fed on either humans or cows. </p><p class="linetext">And they found that bugs with cow blood in their bellies had one partially rearranged chromosome<span class="diff_alert">,</span> compared to those <span class="diff_off">who</span> <span class="diff_add">who'd</span> snacked on human blood <span class="diff_alert">,</span> which could explain the preferences in meal <span class="diff_off">choice</span><span class="diff_add">choices</span>. The study is in the journal PLoS Genetics. </p><p class="linetext">If that genetic switch really does make cows more attractive than we are to <span class="diff_off">mosquitos</span><span class="diff_alert">.</span> <span class="diff_add">mosquitoes</span><span class="diff_alert">,</span> <span class="diff_alert" title="In ">in </span>theory <span class="diff_alert">,</span> we <span class="diff_off">can</span> <span class="diff_add">could</span> genetically engineer them to <span class="diff_off">steal</span> <span class="diff_add">steer</span> clear of people. And their cow victims don't get human malaria. It's a case of knowing your enemy <span class="diff_alert">.</span> <span class="diff_alert" title="And ">and </span>so <span class="diff_alert">,</span> <span class="diff_alert" title="The ">the </span>better we know these <span class="diff_off">mosquitos</span><span class="diff_add">mosquitoes</span>, I think, the more equipped <span class="diff_off">we</span> <span class="diff_off">will</span> <span class="diff_off">gonna</span> <span class="diff_add">we're</span> <span class="diff_add">going</span> <span class="diff_add">to</span> <span class="diff_add">be</span> <span class="diff_add">to</span> be able to control them.</p>
<!--我的听写结束-->



* _Words_ worth to be remembered:
    * fisthand:`adj. 直接的,直接得来的,直接采购的 adv. 直接地`
    * anopheles:`按蚊,按蚊属`
    * steer:`v. 行驶；掌舵；引导；控制`
    * so much so:`以至于`


## 譯文
因为你也许已经亲身经历过了，某些种类的蚊子品尝到了温暖的人类血液。太多次以至于如果你要在实验室里饲养它们，它们什么其它食物都是不吃的。所幸的是，我没有碰到过剧烈的反应。这是加州大学U.C. Davis分校的一位研究蚊子的遗传学家，他还兼职做蚊子的食物供应商。所以对我来讲还不是太差。但是当被几百只蚊子咬过之后，实验室中的某些人可是会感到非常痒的。

在野外，某些种类的胃口还不是很挑剔。 就拿东非地区常见的阿拉伯按蚊来说吧。它们会咬牛，狗，山羊，猪， 和人——只要它们能发现这是一顿温暖的食物。但是，Main和他的同事们想知道是否这些吸血鬼对食物挑剔的结果其实是遗传决定的。所以他们对从坦桑尼亚捉来的已经尝过人或者小牛的血液的48种按蚊。

结果他们就发现，对比已经尝过人学的蚊子，吃过牛血的这种蚊子含有部分重组过后的染色体，这就可以解释为何有些蚊子会有食物偏好。该研究已发表在《公共科学图书馆：遗传学》杂志上。

如果，遗传转换真的使得牛比人类 对这些蚊子更有吸引力的话， 理论上我们能对它们进行遗传修饰以便人类完全引导它们的生活史。而被咬的牛是不会得疟疾的。这只是了解你的对手的一个机会。 所以，我们对这些蚊子了解的约多，我们将会更好的对它们进行掌控。
